<?php
/*
// 说明: 创建系统表
// 作者: 幽兰 (weelia@126.com)
// 时间: 2009-10-07 16:55
*/

$db_tables = array();

$db_tables["patient"] = "CREATE TABLE IF NOT EXISTS `patient_{hid}` (
	`id` int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`yuyue_num` int(10) NOT NULL COMMENT '预约号',
	`order_type` int(4) NOT NULL COMMENT '预约渠道',
	`part_id` int(10) NOT NULL DEFAULT '0' COMMENT '部门',
	`track_status` int(1) NOT NULL DEFAULT '0' COMMENT '跟踪状态',
	`zx_group` varchar(2) NOT NULL DEFAULT '' COMMENT '咨询员分组',
	`name` varchar(20) NOT NULL COMMENT '姓名',
	`age` int(3) NOT NULL COMMENT '年龄',
	`sex` varchar(6) NOT NULL COMMENT '性别',
	`disease_id` int(10) NOT NULL DEFAULT '0' COMMENT '病患类型',
	`disease_2` varchar(100) NOT NULL COMMENT '二级疾病',
	`depart` int(10) NOT NULL DEFAULT '0' COMMENT '科室',
	`tel` varchar(20) NOT NULL COMMENT '电话',
	`tel_location` varchar(40) NOT NULL COMMENT '号码归属地',
	`qq` varchar(20) NOT NULL COMMENT 'QQ号',
	`order_qq` varchar(20) NOT NULL COMMENT '我方QQ',
	`weixin` varchar(20) NOT NULL COMMENT '微信号',
	`order_weixin` varchar(20) NOT NULL COMMENT '我方微信',
	`is_fuzhen` int(1) NOT NULL DEFAULT '0' COMMENT '是否复诊',
	`zhuanjia_num` varchar(10) NOT NULL COMMENT '专家号',
	`wish_doctor` varchar(10) NOT NULL COMMENT '指定医生',
	`content` mediumtext NOT NULL COMMENT '咨询内容',
	`zhusu` text NOT NULL COMMENT '主诉',
	`talk_content` text NOT NULL COMMENT '聊天内容',
	`jiedai` varchar(20) NOT NULL COMMENT '接待',
	`order_date` int(10) NOT NULL DEFAULT '0' COMMENT '预约时间',
	`order_date_changes` int(4) NOT NULL DEFAULT '0' COMMENT '预约时间修改',
	`order_date_log` text NOT NULL COMMENT '预约时间修改日志',
	`order_soft` varchar(6) NOT NULL COMMENT '预约软件',
	`swt_id` varchar(30) NOT NULL COMMENT '商务通永久身份',
	`media_from` varchar(20) NOT NULL COMMENT '媒体来源',
	`qq_from` varchar(20) NOT NULL COMMENT 'QQ来源',
	`tel_from` varchar(20) NOT NULL COMMENT '电话来源',
	`wuxian_from` varchar(20) NOT NULL COMMENT '无线来源',
	`shichang` varchar(12) NOT NULL COMMENT '市场来源',
	`engine` varchar(20) NOT NULL COMMENT '搜索引擎',
	`from_site` varchar(100) NOT NULL COMMENT '来源网站',
	`key_word` varchar(100) NOT NULL COMMENT '搜索关键词',
	`youhuazu` varchar(100) NOT NULL COMMENT '所属优化部门',
	`account` varchar(20) NOT NULL COMMENT '所属帐户',
	`guiji` varchar(20) NOT NULL COMMENT '轨迹',
	`qudao` varchar(20) NOT NULL COMMENT '渠道',
	`tuiguangren` varchar(20) NOT NULL COMMENT '推广人',
	`memo` mediumtext NOT NULL COMMENT '备注',
	`status` int(2) NOT NULL DEFAULT '0' COMMENT '到院状态',
	`zhiliang` int(2) NOT NULL DEFAULT '0' COMMENT '质量',
	`suozaidi` int(2) NOT NULL DEFAULT '0' COMMENT '患者所在地',
	`come_date` int(10) NOT NULL DEFAULT '0' COMMENT '到院时间',
	`xianchang_doctor` varchar(32) NOT NULL COMMENT '现场医生',
	`doctor` varchar(32) NOT NULL COMMENT '主治医生',
	`is_chengjiao` int(2) NOT NULL DEFAULT '0' COMMENT '是否成交',
	`is_xiaofei` int(2) NOT NULL DEFAULT '0' COMMENT '是否消费',
	`xiaofei_count` double(10,1) NOT NULL DEFAULT '0' COMMENT '总消费额',
	`xiaofei_log` mediumtext NOT NULL COMMENT '历次消费记录',
	`is_jiancha` int(2) NOT NULL DEFAULT '0' COMMENT '是否已检查',
	`is_zhiliao` int(2) NOT NULL DEFAULT '0' COMMENT '是否治疗(包括手术)',
	`is_yibao` int(2) NOT NULL DEFAULT '0' COMMENT '是否为医保',
	`xiangmu` varchar(250) NOT NULL COMMENT '治疗项目',
	`rechecktime` int(10) NOT NULL DEFAULT '0' COMMENT '复查时间',
	`huifang_kf` varchar(32) NOT NULL COMMENT '回访客服',
	`huifang` mediumtext NOT NULL COMMENT '回访记录',
	`huifang_nexttime` int(10) NOT NULL DEFAULT '0' COMMENT '下次回访提醒时间',
	`luyin_file` varchar(40) NOT NULL COMMENT '录音文件',
	`upload_uid` int(10) NOT NULL DEFAULT '0' COMMENT '上传者',
	`upload_time` int(10) NOT NULL DEFAULT '0' COMMENT '上传时间',
	`addtime` int(10) NOT NULL DEFAULT '0' COMMENT '添加时间',
	`uid` int(10) NOT NULL DEFAULT '0' COMMENT 'UID',
	`author` varchar(32) NOT NULL COMMENT '添加人',
	`edit_log` text NOT NULL COMMENT '修改记录',
	`sms_skip_send` int(1) NOT NULL DEFAULT '0' COMMENT '勿发短信',
	`from_table` varchar(20) NOT NULL COMMENT '来源表',
	`from_id` int(8) NOT NULL DEFAULT '0' COMMENT '来源表ID',
	`ku_id` int(8) NOT NULL DEFAULT '0' COMMENT '资料库ID',
	`xinmeiti_id` int(8) NOT NULL DEFAULT '0' COMMENT '新媒体库ID',
	`catch_id` int(8) NOT NULL DEFAULT '0' COMMENT '抓取库ID',
	`card_id` varchar(18) NOT NULL COMMENT '身份证编号',
	`repeat_flag` int(1) NOT NULL DEFAULT '0' COMMENT '重复标记',
	PRIMARY KEY (`id`),
	KEY `quick` (`part_id`,`disease_id`,`order_date`,`addtime`,`uid`,`status`,`id`),
	KEY `order_type` (`order_type`),
	KEY `part_id` (`part_id`),
	KEY `addtime` (`addtime`),
	KEY `order_date` (`order_date`),
	KEY `uid` (`uid`),
	KEY `status` (`status`),
	KEY `author` (`author`),
	KEY `name` (`name`),
	KEY `tel` (`tel`)
	) ENGINE=MyISAM DEFAULT CHARSET=gbk AUTO_INCREMENT=1 ;";


?>